/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DBP2P;
import MODEL.User;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import javax.swing.JOptionPane;

/**
 *
 * @author NAUFAL
 */
public class EditProfile extends javax.swing.JFrame {

    static Connection conn;
    static Statement st;
    static String sql;
    PreparedStatement ps;
    static ResultSet rs;
    User user;
    int idnya;
    
    public EditProfile(int id) {
        conn = new DBP2P().setConnection();
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        idnya = id;
        tampilProfile();
    }

    private EditProfile() {
        
    }

     public void tampilProfile(){
        try {
            sql = "SELECT * FROM user WHERE id_user LIKE '"+idnya+"'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                lbId.setText(rs.getString("id_user"));
                tfFullNameEP.setText(rs.getString("fullname"));
                tfUsernameEP.setText(rs.getString("username"));
                tfPasswordEP.setText(rs.getString("password"));
                jxBirthEP.setDate(rs.getDate("birth"));
            }
            
        } catch (Exception e) {
            System.out.println("ERROR"+e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btCancel = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        tfPasswordEP = new javax.swing.JTextField();
        tfFullNameEP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfUsernameEP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        jxBirthEP = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(194, 194, 194));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btCancel.setBackground(new java.awt.Color(143, 38, 41));
        btCancel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btCancel.setForeground(new java.awt.Color(255, 255, 255));
        btCancel.setText("CANCEL");
        btCancel.setBorder(null);
        btCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 434, 257, 36));

        btSave.setBackground(new java.awt.Color(65, 175, 96));
        btSave.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btSave.setForeground(new java.awt.Color(255, 255, 255));
        btSave.setText("SAVE");
        btSave.setBorder(null);
        btSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 380, 257, 36));

        tfPasswordEP.setBackground(new java.awt.Color(255, 255, 255));
        tfPasswordEP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfPasswordEP.setForeground(new java.awt.Color(0, 0, 0));
        tfPasswordEP.setBorder(null);
        jPanel1.add(tfPasswordEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 250, 36));

        tfFullNameEP.setBackground(new java.awt.Color(255, 255, 255));
        tfFullNameEP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfFullNameEP.setForeground(new java.awt.Color(0, 0, 0));
        tfFullNameEP.setBorder(null);
        jPanel1.add(tfFullNameEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 164, 257, 36));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 20, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 226, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Birth Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 334, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(43, 72, 109));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("EDIT PROFILE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 66, 246, 61));

        tfUsernameEP.setBackground(new java.awt.Color(255, 255, 255));
        tfUsernameEP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfUsernameEP.setForeground(new java.awt.Color(0, 0, 0));
        tfUsernameEP.setBorder(null);
        jPanel1.add(tfUsernameEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 218, 257, 36));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Full Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 172, -1, -1));

        lbId.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbId.setForeground(new java.awt.Color(0, 0, 0));
        lbId.setText("jLabel7");
        jPanel1.add(lbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        jxBirthEP.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jxBirthEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        
        this.dispose();
        Profile profile = new Profile(idnya);
        profile.setVisible(true);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
            
            int iduser = Integer.parseInt(lbId.getText());
            String fullname = tfFullNameEP.getText();
            String username = tfUsernameEP.getText();
            String password = tfPasswordEP.getText();
            String tgl = formater.format(jxBirthEP.getDate());

            String dob[] = tgl.split("-");
            int year = Integer.parseInt(dob[0]);
            int month = Integer.parseInt(dob[1]);
            int day = Integer.parseInt(dob[2]);
            LocalDate selectedDate = LocalDate.of(year, month, day);
            LocalDate currentDate = LocalDate.now();
            int resultyear = Period.between(selectedDate, currentDate).getYears();
            
            if(resultyear >= 17){
                
            try {
                sql = "UPDATE user SET " 
                + "fullname = ?, "
                + "username = ?, "
                + "password = ?, "
                + "birth = ? "
                + "WHERE id_user="+iduser;
                ps = conn.prepareStatement(sql);
                ps.setString(1, fullname);
                ps.setString(2, username);
                ps.setString(3, password);
                ps.setString(4, tgl);

                int rt = ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Updated","Edit data",JOptionPane.INFORMATION_MESSAGE);
                    
            } catch (Exception e) {
                System.out.println("ERROR"+e.getMessage());
            }
            }else{
                JOptionPane.showMessageDialog(null, "Must be 17+");
            }
            
    }//GEN-LAST:event_btSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jxBirthEP;
    private javax.swing.JLabel lbId;
    private javax.swing.JTextField tfFullNameEP;
    private javax.swing.JTextField tfPasswordEP;
    private javax.swing.JTextField tfUsernameEP;
    // End of variables declaration//GEN-END:variables
}
