/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DBP2P;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author NAUFAL
 */
public class Register extends javax.swing.JFrame {

    static Connection conn;
    static Statement st;
    static String sql;
    PreparedStatement ps;
    static ResultSet rs;
    int usia;
    
    public Register() {
        conn = new DBP2P().setConnection();
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfPasswordReg = new javax.swing.JPasswordField();
        tfUsernameReg = new javax.swing.JTextField();
        btSignUp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfFullName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jxBirthReg = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(194, 194, 194));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 226, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 280, -1, -1));

        tfPasswordReg.setBackground(new java.awt.Color(255, 255, 255));
        tfPasswordReg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfPasswordReg.setForeground(new java.awt.Color(0, 0, 0));
        tfPasswordReg.setBorder(null);
        jPanel1.add(tfPasswordReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 272, 257, 36));

        tfUsernameReg.setBackground(new java.awt.Color(255, 255, 255));
        tfUsernameReg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfUsernameReg.setForeground(new java.awt.Color(0, 0, 0));
        tfUsernameReg.setBorder(null);
        jPanel1.add(tfUsernameReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 218, 257, 36));

        btSignUp.setBackground(new java.awt.Color(43, 72, 109));
        btSignUp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btSignUp.setText("SIGN UP");
        btSignUp.setBorder(null);
        btSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 380, 257, 36));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Full Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 172, -1, -1));

        tfFullName.setBackground(new java.awt.Color(255, 255, 255));
        tfFullName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfFullName.setForeground(new java.awt.Color(0, 0, 0));
        tfFullName.setBorder(null);
        jPanel1.add(tfFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 164, 257, 36));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Birth Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 334, -1, -1));

        btBack.setBackground(new java.awt.Color(143, 38, 41));
        btBack.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btBack.setForeground(new java.awt.Color(255, 255, 255));
        btBack.setText("BACK");
        btBack.setBorder(null);
        btBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        jPanel1.add(btBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 434, 257, 36));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(43, 72, 109));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("REGISTER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 67, 199, 61));

        jxBirthReg.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jxBirthReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1162, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    private void btSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignUpActionPerformed
        Calendar cals = Calendar.getInstance();
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        
            String fullname = tfFullName.getText();
            String username = tfUsernameReg.getText();
            String password = tfPasswordReg.getText();
            String tgl = formater.format(jxBirthReg.getDate());
            
            //String umur = ((JTextField)jxBirthReg.getDateEditor().getUiComponent()).getText();
            
            String dob[] = tgl.split("-");
            
            int year = Integer.parseInt(dob[0]);
            int month = Integer.parseInt(dob[1]);
            int day = Integer.parseInt(dob[2]);
            
            
            LocalDate selectedDate = LocalDate.of(year, month, day);
            LocalDate currentDate = LocalDate.now();
            
            int resultyear = Period.between(selectedDate, currentDate).getYears();
            
            if(resultyear >= 17){
                 try {
                    sql = "INSERT INTO user VALUES ( ?, ?, ?, ?, ?, ?)";
                    ps = conn.prepareStatement(sql);
                    ps.setInt(1, 0);
                    ps.setString(2, fullname);
                    ps.setString(3, username);
                    ps.setString(4, password);
                    ps.setString(5, tgl);
                    ps.setInt(6, 0);

                    int rt = ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Succeed","Information",JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                        Login login = new Login();
                        login.setVisible(true);
                } catch (Exception e) {
                    System.out.println("ERROR"+e.getMessage());
                }
            }else {
                JOptionPane.showMessageDialog(null, "Must be 17+");
            }
            
       
    }//GEN-LAST:event_btSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jxBirthReg;
    private javax.swing.JTextField tfFullName;
    private javax.swing.JPasswordField tfPasswordReg;
    private javax.swing.JTextField tfUsernameReg;
    // End of variables declaration//GEN-END:variables
}
